Update check1

diff --git a/check1 b/check1
--- a/check1
+++ b/check1
@@ -1,119 +1,109 @@
-zabbix ALL=(db2inst1) NOPASSWD: /path/to/your/script.sh
-
-UserParameter=db2.metrics[*], /tmp/script.sh $1
-
-#!/usr/bin/sh
-
-# DB2 connection details
-DB_USER="your_db_username"
-DB_PASS="your_db_password"
-DB_NAME="pegadb"
-
-# Function to execute DB2 queries
-
-. /home/db2inst1/sqllib/db2profile
-execute_db2_query() {
-    db2 connect to $DB_NAME > /dev/null 2>&1
-    db2 -x "$1"
-}
-
-# Function to get db status
-get_db_status() {
-    execute_db2_query "SELECT DB_STATUS FROM TABLE(MON_GET_DATABASE(-2)) AS T"
-}
-
-# Function to get the database size
-get_database_size() {
-    execute_db2_query "select sum(TBSP_USED_SIZE_KB) / 1024 / 1024 as DATABASE_SIZE from sysibmadm.TBSP_UTILIZATION" | grep -o '[0-9]*' | head -n1
-}
-
-# Function to get active connections
-get_active_connections() {
-    execute_db2_query "SELECT COUNT(*) FROM SYSIBMADM.APPLICATIONS WHERE APPL_STATUS='UOW EXECUTING'" |  tr -d [:space:]
-}
-
-# Function to get lock waits
-get_lock_waits() {
-    execute_db2_query "SELECT COUNT(*) FROM SYSIBMADM.LOCKWAITS;" |  tr -d [:space:]
-
-}
-
-# Function to get log file usage
-get_log_file_usage() {
-    execute_db2_query "select LOG_UTILIZATION_PERCENT from sysibmadm.MON_TRANSACTION_LOG_UTILIZATION" |  tr -d [:space:]
-}
-
-# Function to get table usages
-get_table_usages() {
-    execute_db2_query "SELECT TBSP_USED_PAGES * 100.0 / TBSP_TOTAL_PAGES AS USED_PERCENTAGE FROM SYSIBMADM.TBSP_UTILIZATION" | grep -v 'Division' |  tr -d [:space:]
-}
+#!/bin/bash
 
 
+sed -i 's/\r$//' "$0"
 
-# Call functions to collect data
-db_status=$(get_db_status | sed 's/^[[:space:]]*//')
-lock_waits=$(get_lock_waits | sed 's/^[[:space:]]*//')
-database_size=$(get_database_size | sed 's/^[[:space:]]*//')
-active_connections=$(get_active_connections | sed 's/^[[:space:]]*//')
-log_file_usage=$(get_log_file_usage | sed 's/^[[:space:]]*//')
-table_usages=$(get_table_usages | sed 's/^[[:space:]]*//')
+echo "[`date`]: ########## REMOVE EXISTING ZABBIX ##########"
+systemctl stop zabbix_agentd zabbix-agent2 2>/dev/null
+systemctl disable zabbix_agentd zabbix-agent2 2>/dev/null
+ps -ef | grep zabbix | grep -v grep
 
-# Output data in a format readable by Zabbix
-echo "DatabaseStatus:$db_status"
-echo "DatabaseSize:$database_size"
-echo "ActiveConnections:$active_connections"
-echo "LockWaits:$lock_waits"
-echo "LogFileUsage:$log_file_usage"
-echo "TableUsages:$table_usages"
+# Break all the Zabbix-related links and remove old files
+find /usr /etc /run -type l -name "*zabbix*" -exec unlink {} \;
 
+rpm_name=$(rpm -qa | grep -i 'zabbix-agent2')
+if [[ -n "$rpm_name" ]]; then
+    rpm -e "$rpm_name"
+fi
 
+rpm_zs=$(rpm -qa | grep -i 'zabbix-sender')
+if [[ -n "$rpm_zs" ]]; then
+    rpm -e "$rpm_zs"
+fi
 
+echo "[`date`]: ########## INSTALL NEW ZABBIX ##########"
+OS_VERSION=$(rpm -E %{rhel})
 
-DatabaseStatus:SQL0551N  The statement failed because the authorization ID does not have the 
-required authorization or privilege to perform the operation.  Authorization 
-ID: "ROOT".  Operation: "EXECUTE". Object: "SYSPROC.MON_GET_DATABASE".  
-SQLSTATE=42501
-DatabaseSize:1092
-ActiveConnections:SQL1092NTherequestedcommandoroperationfailedbecausetheuserIDdoesnothavetheauthoritytoperformtherequestedcommandoroperation.UserID:"ROOT".
-LockWaits:SQL1092NTherequestedcommandoroperationfailedbecausetheuserIDdoesnothavetheauthoritytoperformtherequestedcommandoroperation.UserID:"ROOT".
-LogFileUsage:2.62
-TableUsages:SQL1092NTherequestedcommandoroperationfailedbecausetheuserIDdoesnothavetheauthoritytoperformtherequestedcommandoroperation.UserID:"ROOT".
+case $OS_VERSION in
+    7)
+        echo "OS Version is $OS_VERSION"
+        yum install -y pcre2
+        rpm -ivh zabbix-agent2-7.0.5-release1.el7.x86_64.rpm || { echo "Installation failed"; exit 1; }
+        rpm -ivh zabbix-sender-7.0.5-release1.el7.x86_64.rpm
+        systemctl enable zabbix-agent2
+        ;;
+    8)
+        echo "OS Version is $OS_VERSION"
+        yum install -y pcre2
+        rpm -ivh zabbix-agent2-7.0.5-release1.el8.x86_64.rpm || { echo "Installation failed"; exit 1; }
+        rpm -ivh zabbix-sender-7.0.5-release1.el8.x86_64.rpm
+        systemctl enable zabbix-agent2
+        ;;
+    9)
+        echo "OS Version is $OS_VERSION"
+        rpm -ivh zabbix-agent2-7.0.5-release1.el9.x86_64.rpm || { echo "Installation failed"; exit 1; }
+        rpm -ivh zabbix-sender-7.0.5-release1.el9.x86_64.rpm
+        systemctl enable zabbix-agent2
+        ;;
+    *)
+        echo "Unsupported RHEL version"
+        exit 1
+        ;;
+esac
 
+# Update the service file for Zabbix Agent 2
+if [[ -f /usr/lib/systemd/system/zabbix-agent2.service ]]; then
+    sed -i "s/User=zabbix/User=root/g;s/Group=zabbix/Group=root/g" /usr/lib/systemd/system/zabbix-agent2.service
+fi
+systemctl daemon-reload
 
+# Update Zabbix configuration
+if [[ -f /etc/zabbix/zabbix_agent2.conf ]]; then
+    echo "[`date`]: Existing config."
+    egrep -v "^$|^#" /etc/zabbix/zabbix_agent2.conf
 
+    sed -i "s/^Hostname.*/Hostname=`hostname`/g;
+            s/^Server=.*/Server=/g;
+            s/^ServerActive=.*/ServerActive=/g" /etc/zabbix/zabbix_agent2.conf
 
+    sed -i "s/^# UnsafeUserParameters=0/UnsafeUserParameters=1/g;
+            s/# UserParameter=/UserParameter=usercmd[*],\$1/g" /etc/zabbix/zabbix_agent2.conf
 
+    echo "AllowKey=system.run[*]" >> /etc/zabbix/zabbix_agent2.conf
 
+    echo "[`date`]: Updated config."
+    egrep -v "^$|^#" /etc/zabbix/zabbix_agent2.conf
+fi
 
+# Restart Zabbix Agent
+if systemctl list-unit-files | grep -q zabbix-agent2; then
+    systemctl restart zabbix-agent2
+else
+    systemctl restart zabbix-agent2
+fi
 
-
-{ASOMDWFDB404:db2.metrics[LogFileUsage].last(#100)}=0
-
-
-cannot apply multiplier "0.001" to value of type "string": cannot convert value to numeric type
-
-
-Djavax.management.builder.initial=weblogic.management.jmx.mbeanserver.WLSMBeanServerBuilder Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8888 Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false.
-
-JAVA_OPTIONS="$JAVA_OPTIONS -Dcom.sun.management.jmxremote=true"
-JAVA_OPTIONS="$JAVA_OPTIONS -Dcom.sun.management.jmxremote.port=10052"  
-JAVA_OPTIONS="$JAVA_OPTIONS -Dcom.sun.management.jmxremote.ssl=false"  
-JAVA_OPTIONS="$JAVA_OPTIONS -Dcom.sun.management.jmxremote.authenticate=false" 
-
-Potential Conflicts: If another service on your system already uses port 8888, it can lead to conflicts. This could prevent Zabbix from establishing a connection to the WebLogic JMX server, hindering monitoring capabilities.	   
-	   
-Choose a Custom Port: Select a non-standard port number specifically for JMX access in your WebLogic configuration.
+echo "[`date`]: Zabbix Agent setup complete."
 
 
 
-<configuration ...>
-    <... other configurations ...>
-    <subsystem name="jmx">
-        <expose-resolved-address value="true"/>
-        <service url="service:jmx:rmi:///jmxconnector?rmiPort=12345"/>  <connector>
-            <port>${jboss.management.http.port:9990}</port>  <authentication enabled="false">  <user name="your_username" password="your_password"/>  </authentication>
-        </connector>
-    </subsystem>
-    <... other configurations ...>
-</configuration>
 
+
+
+
+
+
+
+
+
+
+
+DR_agent_upgrade_v1.sh: line 2: $'\r': command not found
+DR_agent_upgrade_v1.sh: line 3: $'\r': command not found
+: No such file or directorygrade_v1.sh
+DR_agent_upgrade_v1.sh: line 5: $'\r': command not found
+[Mon Feb 10 22:29:26 +13 2025]: ########## REMOVE EXISTING ZABBIX ##########
+root      166299  166269  0 22:29 pts/0    00:00:00 grep zabbix
+DR_agent_upgrade_v1.sh: line 10: $'\r': command not found
+DR_agent_upgrade_v1.sh: line 13: $'\r': command not found
+DR_agent_upgrade_v1.sh: line 27: syntax error near unexpected token `$'in\r''
+'R_agent_upgrade_v1.sh: line 27: `case $OS_VERSION in
